export const GET_USERS  = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const SHOW_USER = 'SHOW_USER';
export const SELECT_USER = 'SELECT_USER';
export const UNSELECT_USER = 'UNSELECT_USER';
export const ERROR_USER = 'ERROR_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER='EDIT_USER';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const SET_PAGINA_ACTUAL ='SET_PAGINA_ACTUAL';
export const UNSET_PAGINA_ACTUAL ="UNSET_PAGINA_ACTUAL";

export const MOSTRAR_ALERTA='MOSTRAR_ALERTA';
export const OCULTAR_ALERTA='OCULTAR_ALERTA';

export const GET_PERSONS ="GET_PERSONS";
export const ADD_PERSON="ADD_PERSON";
export const EDIT_PERSON="EDIT_PERSON";
export const DELETE_PERSON="DELETE_PERSON";
export const SELECT_PERSON="SELECT_PERSON";
export const UNSELECT_PERSON="UNSELECT_PERSON";
export const SHOW_PERSON="SHOW_PERSON";
export const INFO_PERSONS="INFO_PERSONS";
export const SET_ACTIVE_PAGE_PERSONS="SET_ACTIVE_PAGE_PERSONS";

export const GET_DEPENDENCIES  = 'GET_DEPENDENCIES';
export const ERROR_DEPENDENCIE = 'ERROR_DEPENDENCIE';




