export const GET_USERS  = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const SHOW_USER = 'SHOW_USER';
export const SELECT_USER = 'SELECT_USER';
export const UNSELECT_USER = 'UNSELECT_USER';
export const ERROR_USER = 'ERROR_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER='EDIT_USER';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const RESET_MESSAGE = 'RESET_MESSAGE';

export const GET_PERSONAL ="GET_PERSONAL";
export const ADD_PERSONAL="ADD_PERSONAL";
export const EDIT_PERSONAL="EDIT_PERSONAL";
export const DELETE_PERSONAL="DELETE_PERSONAL";
export const SELECT_PERSONAL="SELECT_PERSONAL";
export const UNSELECT_PERSONAL="UNSELECT_PERSONAL";
export const SHOW_PERSON="SHOW_PERSON";
export const ERROR_PERSONAL="ERROR_PERSONAL";

export const GET_DEPENDENCIES  = 'GET_DEPENDENCIES';
export const ERROR_DEPENDENCIE = 'ERROR_DEPENDENCIE';




