export const OBTENER_USUARIOS  = 'OBTENER_USUARIOS';
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const VER_USUARIO = 'VER_USUARIO';
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO';
export const DESELECCIONAR_USUARIO = 'DESELECCIONAR_USUARIO';
export const ERROR_USUARIO = 'ERROR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const REINICIAR_MENSAJE = 'REINICIAR_MENSAJE';
export const EDITAR_USUARIO='EDITAR_USUARIO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

